{
 "title": "Comparação Nginx × Apache",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests por segundo",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[30s])",
     "legendFormat": "Nginx"
    },
    {
     "expr": "rate(apache_accesses_total[30s])",
     "legendFormat": "Apache"
    }
   ]
  },
  {
   "title": "Uso de RAM",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / (1024 * 1024)",
     "legendFormat": "RAM (MB)"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Tempo de resposta médio (Apache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(apache_duration_ms_total[30s]) \r\n/\r\nrate(apache_accesses_total[30s])\r\n",
     "legendFormat": "Tempo Médio"
    }
   ]
  },
  {
   "title": "Quantidade de dados enviados (Apache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(apache_sent_kilobytes_total[30s])",
     "legendFormat": "throughput (KB/s)"
    }
   ]
  },
  {
   "title": "Conexões ativas (Nginx)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "nginx_connections_active\r\n", "legendFormat": "Conexões Ativas" },
    { "expr": "nginx_connections_reading", "legendFormat": "Leituras" },
    { "expr": "nginx_connections_writing", "legendFormat": "Escrita" },
    { "expr": "nginx_connections_waiting", "legendFormat": "Em Espera" }
   ]
  }
 ]
}