server {
    listen 80;
    server_name localhost;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    add_header X-Custom-ID $http_x_custom_id always;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /leve {
        alias /usr/share/nginx/html/leve.txt;
    }

    location /medio {
        alias /usr/share/nginx/html/medio.txt;
    }

    location /pesado {
        alias /usr/share/nginx/html/pesado.txt;
    }

    location /stub_status {
        stub_status;
        access_log off;
    }
}
