ServerRoot "/usr/local/apache2"
Listen 80
ServerAdmin you@example.com
ServerName localhost


LoadModule mpm_worker_module modules/mod_mpm_worker.so
LoadModule status_module modules/mod_status.so
LoadModule alias_module modules/mod_alias.so
LoadModule headers_module modules/mod_headers.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule dir_module modules/mod_dir.so

<IfModule dir_module>
    DirectoryIndex index.html
</IfModule>

ErrorLog /usr/local/apache2/logs/error.log
CustomLog /usr/local/apache2/logs/access.log combined

<IfModule mod_headers.c>
    RequestHeader set X-Custom-ID "%{X-Custom-ID}i"
</IfModule>

DocumentRoot "/usr/local/apache2/htdocs"

<Directory "/usr/local/apache2/htdocs">
    AllowOverride None
    Require all granted
</Directory>

<Files "index.html">
    Require all granted
</Files>

Alias /leve "/usr/local/apache2/htdocs/leve.txt"
Alias /medio "/usr/local/apache2/htdocs/medio.txt"
Alias /pesado "/usr/local/apache2/htdocs/pesado.txt"

<FilesMatch ".*">
    Require all granted
</FilesMatch>

<Location "/server-status">
    SetHandler server-status
    Require all granted
</Location>

ExtendedStatus On
